// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daamkldzorjgkxgbwqqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhYW1rbGR6b3JqZ2t4Z2J3cXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTkxNTgsImV4cCI6MjA2Mjc5NTE1OH0.EDVOE478krhZA0_vHrdyzkgwcifz4en19hqv_ZzinlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);